### ISSUE TITLE
Hi, Could you update the speed of your caffemodel?

### ISSUE THREAD

**Issue by weitaoatvison** [TimoSaemann/ENet#1]
Hi, I tested the speed of your caffemodel on my PC(TITAN X,  CUDA8.0, CUDNN5.1), When the resolution of the input image is  512 * 1024, the speed is 1.96s/Frame on cpu and 0.64s/Frame on GPU. There is a big gap with the paper. So, could you update your test result on github? Thanks!

**Comment by TimoSaemann** [comment]
Hi,
Thanks for the reminder! I have uploaded a performance comparison in README.md and added the command to reproduce the values to the tutorial.

Some reasons why my values are slightly slower than the ones in the paper are:

- Hardware setup:
When I repeat the measurements with a different hardware setup: P100, Intel Xeon E5-2680 v4 @2.4 GHz, the run times are significantly lower. For an input size 1280x720 px, the run time is reduced from 35.0 ms to 24.9 ms, although the P100 has just 10 TFLOPS (Titan X Pascal has 11). The point is that the CPU is important as well. 

- Different tool for time measurement 
- 2 bn layers could be merged in deconv filters, which is not done yet (~1.5 ms)
- I don't use a padding layer like the authors in torch. Instead I use a conv layer to adjust the number of feature maps (~0.5 ms)
- Implementation details between Caffe and Torch
