### ISSUE TITLE
How to use the multiple gpu?

### ISSUE THREAD

**Issue by chamcham115** [TimoSaemann/ENet#11]
How to train using multiple gpu?

**Comment by TimoSaemann** [comment]
Since _spatial dropout_ is not a standard layer in Caffe, I have implemented it with python.

Unfortunately, python layer doesn't support Multi-GPU training. If you like to train ENet with multiple GPU's, you have have to implement the _spatial dropout_ layer with C++ (.cpp) or C++/Cuda (.cu).

**Comment by chamcham115** [comment]
Thanks~
