### ISSUE TITLE
PythonLayer is not imlemented in Multi-GPU training

### ISSUE THREAD

**Issue by An-Pan** [TimoSaemann/ENet#53]
Hi, I have try to training using multi-gpu . I got this error  

>[python_layer.hpp:25] PythonLayer is not implemented in Multi-GPU training

So, does any one have experience on change the code spatial_dropout.py to use multi-gpu ?

**Comment by ewen1024** [comment]
As far as I know, python layer is computed through cpu. So forget about multi-gpu

**Comment by An-Pan** [comment]
@ewen1024  Tanks~

**Comment by ewen1024** [comment]
@An-Pan  Meanwhile, I found the spatial drop taking so much time. I simply replaced it with the original verision of dropout  and got nearly 2X speed and no noticeable performance drop.
