### ISSUE TITLE
Low test accuracy with released cityscapes_weights_before_bn_merge.caffemodel

### ISSUE THREAD

**Issue by xurannlpr** [TimoSaemann/ENet#57]
1             road: 0.3766
  2         sidewalk: 0.0000
  3         building: 0.0000
  4             wall: 0.0000
  5            fence: 0.0000
  6             pole: 0.0001
  7    traffic light: 0.0000
  8     traffic sign: 0.0000
  9       vegetation: 0.0000
 10          terrain: 0.0000
 11              sky: 0.0000
 12           person: 0.0000
 13            rider: 0.0000
 14              car: 0.0000
 15            truck: 0.0000
 16              bus: 0.0000
 17            train: 0.0000
 18       motorcycle: 0.0000
 19          bicycle: 0.0000
Mean IoU over 19 classes: 0.0198
Pixel-wise Accuracy: 37.66%

this is the test accuracy of the released cityscapes_weights_before_bn_merge.caffemodel on the cityscapes validation dataset. Does anybody know what's the reason behind this.

**Comment by jianbozhanghit** [comment]
@xurannlpr Hi, I met the same problem, could you please tell me how to solve it?
