### ISSUE TITLE
[Q] When I train on ENet, I met the error

### ISSUE THREAD

**Issue by chamcham115** [TimoSaemann/ENet#6]
Hello, 
I have a question. 

When I train, I met the error. 

--------------------------------------------------------------------------
I0626 10:41:47.785637  4806 layer_factory.hpp:77] Creating layer data
I0626 10:41:47.786315  4806 net.cpp:100] Creating Layer data
I0626 10:41:47.786324  4806 net.cpp:408] data -> data
I0626 10:41:47.786337  4806 net.cpp:408] data -> label
I0626 10:41:47.786352  4806 dense_image_data_layer.cpp:50] Opening file dataset/train_fine_cityscapes.txt
I0626 10:41:47.788602  4806 dense_image_data_layer.cpp:60] Shuffling data
I0626 10:41:47.789371  4806 dense_image_data_layer.cpp:65] A total of 2975 examples.
I0626 10:41:47.857427  4806 dense_image_data_layer.cpp:118] output data size top[0]: 3,3,512,1024
I0626 10:41:47.857450  4806 dense_image_data_layer.cpp:121] output data size top[1]: 3,1,64,128
I0626 10:41:47.862567  4806 net.cpp:150] Setting up data
I0626 10:41:47.862602  4806 net.cpp:157] Top shape: 3 3 512 1024 (4718592)
I0626 10:41:47.862608  4806 net.cpp:157] Top shape: 3 1 64 128 (24576)
I0626 10:41:47.862612  4806 net.cpp:165] Memory required for data: 18972672
I0626 10:41:47.862619  4806 layer_factory.hpp:77] Creating layer data_data_0_split
I0626 10:41:47.862988  4806 net.cpp:100] Creating Layer data_data_0_split
I0626 10:41:47.862996  4806 net.cpp:434] data_data_0_split <- data
I0626 10:41:47.863008  4806 net.cpp:408] data_data_0_split -> data_data_0_split_0
I0626 10:41:47.863015  4806 net.cpp:408] data_data_0_split -> data_data_0_split_1
I0626 10:41:47.863376  4806 net.cpp:150] Setting up data_data_0_split
I0626 10:41:47.863386  4806 net.cpp:157] Top shape: 3 3 512 1024 (4718592)
I0626 10:41:47.863391  4806 net.cpp:157] Top shape: 3 3 512 1024 (4718592)
I0626 10:41:47.863394  4806 net.cpp:165] Memory required for data: 56721408
I0626 10:41:47.863415  4806 layer_factory.hpp:77] Creating layer label_data_1_split
I0626 10:41:47.863423  4806 net.cpp:100] Creating Layer label_data_1_split
I0626 10:41:47.863430  4806 net.cpp:434] label_data_1_split <- label
I0626 10:41:47.863436  4806 net.cpp:408] label_data_1_split -> label_data_1_split_0
I0626 10:41:47.863445  4806 net.cpp:408] label_data_1_split -> label_data_1_split_1
I0626 10:41:47.863474  4806 net.cpp:150] Setting up label_data_1_split
I0626 10:41:47.863483  4806 net.cpp:157] Top shape: 3 1 64 128 (24576)
I0626 10:41:47.863488  4806 net.cpp:157] Top shape: 3 1 64 128 (24576)
I0626 10:41:47.863493  4806 net.cpp:165] Memory required for data: 56918016
I0626 10:41:47.863497  4806 layer_factory.hpp:77] Creating layer conv0_1
I0626 10:41:47.863513  4806 net.cpp:100] Creating Layer conv0_1
I0626 10:41:47.863519  4806 net.cpp:434] conv0_1 <- data_data_0_split_0
I0626 10:41:47.863526  4806 net.cpp:408] conv0_1 -> conv0_1
F0626 10:41:48.349544  4806 cudnn.hpp:113] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
    @     0x7f0005e46daa  (unknown)
    @     0x7f0005e46ce4  (unknown)
    @     0x7f0005e466e6  (unknown)
    @     0x7f0005e49687  (unknown)
    @     0x7f00064a3dc6  caffe::CuDNNConvolutionLayer<>::Reshape()
    @     0x7f0006433045  caffe::Net<>::Init()
    @     0x7f0006433ed5  caffe::Net<>::Net()
    @     0x7f00063cccea  caffe::Solver<>::InitTrainNet()
    @     0x7f00063cdefc  caffe::Solver<>::Init()
    @     0x7f00063ce22a  caffe::Solver<>::Solver()
    @     0x7f00063d7b33  caffe::Creator_AdamSolver<>()
    @           0x411ff6  caffe::SolverRegistry<>::CreateSolver()
    @           0x40af72  train()
    @           0x4089ac  main
    @     0x7f000441af45  (unknown)
    @           0x4092b3  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

my cudnn version is 5.1.0

**Comment by twmht** [comment]
@chamcham115 

I have the same problem, how did you solve it?

**Comment by ChidanandKumarKS** [comment]
@chamcham115  and @twmht 
Have u solved the above problem?, kindly let us know since iam also facing the same issue

**Comment by twmht** [comment]
@ChidanandKumarKS 

please try

```
ldd $build_caffe/tools/caffe | grep cudnn
```

if the version of cudnn is 6,  then you should link cudnn5.

**Comment by KamalM8** [comment]
@twmht Were you able to resolve this error? I am already using cudNN 5.
