### ISSUE TITLE
Really bad performance on TX2

### ISSUE THREAD

**Issue by IAmSaad** [TimoSaemann/ENet#63]
The ENet paper claims to have 21fps on TX1 at the resolution 480*320 but I am getting 2fps (400ms forward pass time). Is there some kind of optimization that needs to be done.

**Comment by sunmiaozju** [comment]
@IAmSaad hello，could I know which jetpack you used in the TX2 ? And how you deploy the ENet on the TX2 ? We also tried to deploy the ENet on the TX2 but maybe there is something wrong. Thank you very much!

**Comment by IAmSaad** [comment]
We used the Jetpack 3.0 I guess. Try to find the use_cpu or use_gpu (I don't remember exactly what they were called) but the basic problem with our setup was that the these were not setup properly. We were running in the CPU mode before we found out about the switches. After that, we were getting like 10fps for 480*360 input.

**Comment by softbai** [comment]
> We used the Jetpack 3.0 I guess. Try to find the use_cpu or use_gpu (I don't remember exactly what they were called) but the basic problem with our setup was that the these were not setup properly. We were running in the CPU mode before we found out about the switches. After that, we were getting like 10fps for 480*360 input.

@IAmSaad  
Can I ask that how did you run the scripts by using pre-trained model? I test the time that the code 
"prediction = net.blobs['deconv6_0_0'].data[0].argmax(axis=0)" needs 2s while inference just uses 0.3s.
Can you tell me the script you used? Thank you!

**Comment by softbai** [comment]
@IAmSaad
