### ISSUE TITLE
ImportError: No module named spatial dropout

### ISSUE THREAD

**Issue by chamcham115** [TimoSaemann/ENet#7]
I0626 19:33:00.715394 10046 net.cpp:100] Creating Layer bn1_0_2
I0626 19:33:00.715397 10046 net.cpp:434] bn1_0_2 <- conv1_0_2
I0626 19:33:00.715414 10046 net.cpp:408] bn1_0_2 -> bn1_0_2
I0626 19:33:00.715584 10046 net.cpp:150] Setting up bn1_0_2
I0626 19:33:00.715590 10046 net.cpp:157] Top shape: 4 64 128 256 (8388608)
I0626 19:33:00.715593 10046 net.cpp:165] Memory required for data: 394657792
I0626 19:33:00.715602 10046 layer_factory.hpp:77] Creating layer drop1_0_3
ImportError: No module named spatial_dropout
*** Aborted at 1498473180 (unix time) try "date -d @1498473180" if you are using GNU date ***
PC: @     0x7f5b31ba7a95 caffe::Blob<>::~Blob()
*** SIGSEGV (@0x7f5b321d02b8) received by PID 10046 (TID 0x7f5b3239ca40) from PID 840762040; stack trace: ***
    @     0x7f5b2fc1acb0 (unknown)
    @     0x7f5b31ba7a95 caffe::Blob<>::~Blob()
    @     0x7f5b31c3fed8 caffe::BasePrefetchingDataLayer<>::~BasePrefetchingDataLayer()
    @     0x7f5b31c797d4 caffe::DenseImageDataLayer<>::~DenseImageDataLayer()
    @     0x7f5b31c79909 caffe::DenseImageDataLayer<>::~DenseImageDataLayer()
    @           0x40e226 std::vector<>::~vector()
    @     0x7f5b31c1f098 caffe::Net<>::Net()
    @     0x7f5b31bb7cea caffe::Solver<>::InitTrainNet()
    @     0x7f5b31bb8efc caffe::Solver<>::Init()
    @     0x7f5b31bb922a caffe::Solver<>::Solver()
    @     0x7f5b31bc2b33 caffe::Creator_AdamSolver<>()
    @           0x411ff6 caffe::SolverRegistry<>::CreateSolver()
    @           0x40af72 train()
    @           0x4089ac main
    @     0x7f5b2fc05f45 (unknown)
    @           0x4092b3 (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by chamcham115** [comment]
solved

**Comment by ChidanandKumarKS** [comment]
KIndly let me know how to solve this issue since iam stuck at this point on this error.d
Regards
Kumar

**Comment by sawakk** [comment]
@chamcham115 Can you help me?
I have the same error

**Comment by nascimentocrafael** [comment]
@chamcham115 Could you please explain us how to solve this issue? I have the same error.

**Comment by nascimentocrafael** [comment]
Solved this by doing the following:

make WITH_PYTHON_LAYER=1 -j 8
make pycaffe

On my bashrc file:

export CAFFE_ENET_HOME=ENet/caffe-enet/
export PYTHONPATH=$CAFFE_ENET_HOME/python

**Comment by sawakk** [comment]
@nascimentocrafael   thank you
Could you help with one more problem?
https://github.com/TimoSaemann/ENet/issues/24
