### ISSUE TITLE
Spattial_Dropout error wbhhile training

### ISSUE THREAD

**Issue by ChidanandKumarKS** [TimoSaemann/ENet#9]
Hai,

During training of an encoder iam met with Import error:no module named spatial_dropout. 
Kindly suggest me how to solve this issue since iam under  job pressure to get some decent results.
Kindly do the needful.

Regards
Kumar

**Comment by ChidanandKumarKS** [comment]
Solved ...

**Comment by sawakk** [comment]
@ChidanandKumarKS How you solved the problem?

**Comment by ChidanandKumarKS** [comment]
$ WITH_PYTHON_LAYER := 1  and build
export PYTHONPATH="$CAFFE_PATH/python:$PYTHONPATH"

will solve the problem

**Comment by sawakk** [comment]
@ChidanandKumarKS  thank you
Could you help with one more problem?
https://github.com/TimoSaemann/ENet/issues/24
